### ISSUE TITLE
tunnels are restarted every time highstate runs

### ISSUE THREAD

**Issue by cmclaughlin** [saltstack-formulas/openvpn-formula#119]
I recently upgraded to the latest version of this formula for systemd suppor (on AWS Linux 2).

And I noticed every time I run highstate my tunnels are restarted.

```
          ID: obsolete_openvpn_employees-udp-1194_service
    Function: service.dead
        Name: openvpn@employees-udp-1194
      Result: True
     Comment: Service openvpn@employees-udp-1194 has been disabled, and is dead
     Started: 04:51:09.669200
    Duration: 250.489 ms
     Changes:
              ----------
              openvpn@employees-udp-1194:
                  True
----------
          ID: openvpn_employees-udp-1194_service
    Function: service.running
        Name: openvpn@employees-udp-1194
      Result: True
     Comment: Service openvpn@employees-udp-1194 has been enabled, and is running
     Started: 04:51:10.094798
    Duration: 254.426 ms
     Changes:
              ----------
              openvpn@employees-udp-1194:
                  True
```

In `service.sls` there's a comment "For an successful upgrade we need to make sure the old services are deactivated". I guess there's a bug on the name of the old service though? It's not clear what case we're trying to cover here. Perhaps we can just delete the entire `service.dead` block?

**Comment by cmclaughlin** [comment]
@aboe76 I noticed you added `service.dead` in #110. I don't have any BSD or Debian hosts... and it's not clear what upgrade case you were working on. Do your tunnels get restarted every time highstate is applied?

**Comment by n-rodriguez** [comment]
> it's not clear what upgrade case you were working on

migration from openvpn@service to openvpn-server@service systemd units.

**Comment by cmclaughlin** [comment]
Ok, so I suppose there's a bug such that I ended up with `openvpn@service` not `openvpn-server@service` - on AWS Linux 2.

**Comment by myii** [comment]
Just a quick note, we've got Amazon Linux 2 configured in [`kitchen.yml'](https://github.com/saltstack-formulas/openvpn-formula/blob/94f6770f3170e7411d4916f08463cd3868b98b09/kitchen.yml) but it isn't currently enabled in [Travis](https://github.com/saltstack-formulas/openvpn-formula/blob/94f6770f3170e7411d4916f08463cd3868b98b09/.travis.yml).  Looking back through the build history, there's a failure at the installation stage:

https://travis-ci.org/myii/openvpn-formula/jobs/574197634#L875:

```
                 ID: openvpn_pkgs
           Function: pkg.installed
             Result: False
            Comment: Error occurred installing package(s). Additional info follows:
              
              errors:
                  - Running scope as unit run-261.scope.
                    Loaded plugins: ovl, priorities
                    No package openvpn available.
                    Error: Nothing to do
```

@cmclaughlin Did you already have `openvpn` installed before using this formula?  Could you suggest the improvements needed to get the installation working here?

**Comment by cmclaughlin** [comment]
> Did you already have openvpn installed before using this formula? Could you suggest the improvements needed to get the installation working here?

Yes and no...

I had an older EC2 instance running that was built off an older version of this formula. I ran a highstate with test=True and saw too many changes to feel comfortable proceeding. So I launched a new instance off the latest version of the formula.

So basically, no, I didn't perform the upgrade.

**Comment by myii** [comment]
@cmclaughlin Do you know what the package name is on Amazon Linux 2?

**Comment by cmclaughlin** [comment]
The package name is just `openvpn` - installed from EPEL 7.

**Comment by myii** [comment]
OK, thanks.  The repo will need to be enabled to install the package.

**Comment by myii** [comment]
@cmclaughlin Thanks, adding the repo worked:

* https://travis-ci.org/myii/openvpn-formula/builds/583326179

@javierbertoli Can the EPEL repo be added to the pre-salted images or should we really be installing the repo using this formula before package installation?

**Comment by myii** [comment]
@daks I had a search through the whole SaltStack Formulas organisation, to see what other formulas do.  There are one or two (e.g. `zfs-formula`), which actually use the `epel-formula` as a dependency but that's not recommended here.  Quite a few use the `epel-formula` as a dependency in Kitchen and that may be something worth considering.  I couldn't find an example of using `pkgrepo` for this.  Probably because it can be [configured](https://aws.amazon.com/premiumsupport/knowledge-center/ec2-enable-epel/) using:

```bash
$ yum install -y https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
```

**Comment by n-rodriguez** [comment]
Why not using the repo pattern?

**Comment by myii** [comment]
@n-rodriguez The repo pattern could definitely be useful.  The issue right now is getting `pkgrepo.managed` working for the EPEL repo -- have you got any experience with this?

**Comment by n-rodriguez** [comment]
> ```shell
> https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
> ```

The content of https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm should help ;)

There's the key and the repo : 

```sh
[epel]
name=Extra Packages for Enterprise Linux 7 - $basearch
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-7&arch=$basearch
failovermethod=priority
enabled=1
gpgcheck=1
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7

[epel-debuginfo]
name=Extra Packages for Enterprise Linux 7 - $basearch - Debug
#baseurl=http://download.fedoraproject.org/pub/epel/7/$basearch/debug
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-debug-7&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=1

[epel-source]
name=Extra Packages for Enterprise Linux 7 - $basearch - Source
#baseurl=http://download.fedoraproject.org/pub/epel/7/SRPMS
metalink=https://mirrors.fedoraproject.org/metalink?repo=epel-source-7&arch=$basearch
failovermethod=priority
enabled=0
gpgkey=file:///etc/pki/rpm-gpg/RPM-GPG-KEY-EPEL-7
gpgcheck=1
```

**Comment by n-rodriguez** [comment]
> Copy/paste in formula pillars (`defaults.yaml` and friends) if users can use the new `openvpn.repo` state or in test pillars (like in `php-formula`) if the state is not meant to be used.

From a global perspective, I think it could be nice to implement the repo pattern as soon as the package can be downloaded from a different repo than the distribution.

By default we should rely on distribution packages. 

But with the repo pattern, people could feed pillars with the repo they want to use and call the `<formula>.repo` state when needed.

What do you think?

**Comment by myii** [comment]
@n-rodriguez Thanks for digging into that, great result.

> From a global perspective, I think it could be nice to implement the repo pattern as soon as the package can be downloaded from a different repo than the distribution.
> 
> By default we should rely on distribution packages.
> 
> But with the repo pattern, people could feed pillars with the repo they want to use and call the `<formula>.repo` state when needed.
> 
> What do you think?

I think it's an excellent idea.  The macro can distributed using the `ssf-formula` as well (for ease of long-term maintenance, should it be improved over time).  My question is whether it wouldn't be easier to have separate files for each macro rather than a generalised `macros.jinja`, a bit like how we did with `libtofs.jinja`?  However, perhaps it's not worth it for small, general-purpose macros such as `format_kwargs`.

**Comment by myii** [comment]
The above links back to: https://github.com/saltstack-formulas/template-formula/pull/134.

**Comment by myii** [comment]
@n-rodriguez This looks good for the EPEL repo:

* https://github.com/saltstack-formulas/epel-formula/pull/51

**Comment by daks** [comment]
@myii I saw those links and understand part of what is done, but I don't know this php-formula and wanted a 'high level' view of the functionality. My main concern is to keep the possibility of having an external way of handling a repo and though not using the one provided by the formula. Some users will always want to keep their repos managed uniformly accross their minions and not depends on formulas.

**Comment by myii** [comment]
@daks Don't worry, I'm not pushing for formula inter-dependencies yet.  That talk can begin if we get the SPM solution that's been discussed on Slack.

In the meantime, my proposal is to use https://github.com/saltstack-formulas/epel-formula/pull/51 directly in this formula, ideally using the "repo pattern" suggested by @n-rodriguez.

**Comment by n-rodriguez** [comment]
> My question is whether it wouldn't be easier to have separate files for each macro rather than a generalised `macros.jinja`, a bit like how we did with `libtofs.jinja`? However, perhaps it's not worth it for small, general-purpose macros such as `format_kwargs`.

I'm for one macro / one file. The best would be to store them in a `macros` directory.
Easier to maintain, easier to extend/change/evolve, easier to copy/paste from one formula to another.

**Comment by myii** [comment]
@daks @n-rodriguez So I've got it working by making the following modification (ignore the `.travis.yml` changes, that's just for testing):

* https://github.com/myii/openvpn-formula/commit/13ab384714fa1115bae94b2b4a8b7dbb13d8b1d1#diff-ea3489002e240c1ef44179e773d6e55d

That's taken directly from the `epel-formula`, including https://github.com/saltstack-formulas/epel-formula/pull/51.  So it doesn't look like the "repo pattern" is going to work here, unless I'm missing something.  Any suggestions on how to proceed with this?

**Comment by daks** [comment]
> @daks Don't worry, I'm not pushing for formula inter-dependencies, at least not yet! That talk can begin if we get the SPM solution that's been discussed on Slack.

When I see all commits/merge/releases which generate a single change in `template-formula`, I still think it may be simpler to have some 'stdlib' one. _(as already discussed elsewhere previously)_

But my point was not there, I just wanted to understand what does this `repo` pattern implies.

> My main concern is to keep the possibility of having an external way of handling a repo and therefore not use the one provided by the formula. Some users will always want to keep their repos managed uniformly accross their minions and not depends on formulas.

**Comment by myii** [comment]
@daks @n-rodriguez Got EPEL repo configured using `pkgrepo.managed` and enabled `amazonlinux-2` in Travis: #122.

**Comment by myii** [comment]
@cmclaughlin What specific states are/were running in your highstate?  We can try to reproduce the issue here, as a first step towards fixing it.

**Comment by cmclaughlin** [comment]
Thanks for all of the effort here... my state simply includes:

```yaml
  - openvpn
  - openvpn.config
  - openvpn.service
```

**Comment by myii** [comment]
@cmclaughlin I've tested this and it should fix your issue:

* https://github.com/myii/openvpn-formula/compare/62fc957c2a39...be7dd345b34f

If you can confirm that, I can put a PR in.

**Comment by cmclaughlin** [comment]
@myii yes, looks good... thanks!

```yaml
          ID: openvpn_employees-udp-1194_service
    Function: service.running
        Name: openvpn@employees-udp-1194
      Result: True
     Comment: The service openvpn@employees-udp-1194 is already running
     Started: 17:16:25.315642
    Duration: 38.392 ms
     Changes:
```

**Comment by myii** [comment]
@cmclaughlin Great, thanks for the confirmation.
