### ISSUE TITLE
Formula does not write individual systemd units for each server, causing service startup to not do anything

### ISSUE THREAD

**Issue by spoage** [saltstack-formulas/openvpn-formula#24]
Discovered on Ubuntu Server 15.04 install. The systemd unit it (salt, not the formula) installs is literally worthless in the case of OpenVPN. Each server entry must be given its own unit and be independently enabled.

**Comment by puneetk** [comment]
@whiteinge thoughts

**Comment by whiteinge** [comment]
I'm not up to speed enough on the move to systemd to be immediately helpful here. I know there's an issue or two filed in the main Salt repo specifically about support for systemd on recent Ubuntus (saltstack/salt#23122).

Broadly, I can recommend the following troubleshooting steps:

1. Where exactly is the breakage? Does the OpenVPN package on 15.04 do the correct thing when installed without Salt? If so:
2. Is there any required debconf configuration that must be done prior to having Salt install the OpenVPN package?
3. Once the package is installed can Salt correctly start/stop the service?
4. Once the service is running does this formula take into account the switch to systemd and can configure the service correctly? If not, what are the missing steps/files/locations?

**Comment by spoage** [comment]
I think perhaps the issue I'm attempting to describe is coming across wrong. I'm putting together a small patch to the formula which might illustrate the problem a bit better. Stand by, and I'll have it up shortly

**Comment by spoage** [comment]
b83c43e fixes the issue for me. I didn't test from a fresh system install, but I did test by uninstalling/purging OpenVPN and then installing it again via the formula.

To elaborate, what I was trying to explain is that the formula doesn't set up systemd entries for each server it generates a configuration for, and that is necessary. The fix (in theory) is to thus add set up an additional 'service' for each server defined.

Does that make a bit more sense?

**Comment by whiteinge** [comment]
Looks straightforward. Thanks for the fix! Please do send a pull req. :smile:

**Comment by diegofd** [comment]
Could this problem be related with this bug? https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=792880

**Comment by alxwr** [comment]
#50 and #49 fixed this issue on a broader basis. Closing (for now).
