### ISSUE TITLE
Problems with this formula being a github fork

### ISSUE THREAD

**Issue by ek9** [saltstack-formulas/openvpn-formula#53]
There are a few issues regarding this formula being a linked github fork:

1. It cannot be found via search ( https://github.com/search?utf8=%E2%9C%93&q=openvpn+formula )
2. Any type of contributions on this formula do not show in contributor's activity graphs

The first one being really bad.

It is possible to solve this by one of these steps (depending which one is easiest to accompish for the maintainers of the project):

Solution is someone from the organization owners emailing github support and asking them to unlink the "fork" link. Everything will be the same, we will only loose the "fork from daschatten/locale-fromula" message below the repositories name at the top. This will fix the mentioned problems.

**Comment by blbradley** [comment]
I have e-mailed GitHub. If they do not accept my request, I'll forward this issue to someone that can authorize it.

**Comment by blbradley** [comment]
They accepted my request. Closing!
