### ISSUE TITLE
config.auth_user_pass: no split needed

### ISSUE THREAD

**Issue by alxwr** [saltstack-formulas/openvpn-formula#71]
https://github.com/saltstack-formulas/openvpn-formula/pull/69#issuecomment-323763459

**Comment by dafyddj** [comment]
Hi @alxwr, 

what is the reason for ```split()[0]``` generally in ```config.sls```? It appears in several places.
I've just realised it prevents me using a file with spaces in its name. (Quite common on Windows!)

**Comment by alxwr** [comment]
Hi @dafyddj,

`split()]0]` gets the first part of a space-separated parameter. See for example `--tls-auth` in https://community.openvpn.net/openvpn/wiki/Openvpn24ManPage.

> I've just realised it prevents me using a file with spaces in its name. (Quite common on Windows!)

They are not uncommon in Linux and BSD too. Our only option seems to be a change in Pillar:

```sls
# from
    tls_auth: /path/to/tls.key 0

# to
    tls_auth:
      - /path/to/tls.key
      - 0
```

But we've got to ensure backwards compatibility. Therefore we should use a (building block) macro which distinguishes between `string` and `list`

I'll fix this as part of this issue.
